CREATE TABLE role
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (user_id)
);

CREATE TABLE session
(
    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token          VARCHAR(255),
    expiring_at    TIMESTAMP WITHOUT TIME ZONE,
    log_in_at      TIMESTAMP WITHOUT TIME ZONE,
    user_user_id   BIGINT,
    session_status SMALLINT,
    CONSTRAINT pk_session PRIMARY KEY (user_id)
);

CREATE TABLE users
(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE users_roles
(
    users_user_id BIGINT NOT NULL,
    roles_user_id BIGINT NOT NULL,
    CONSTRAINT pk_users_roles PRIMARY KEY (users_user_id, roles_user_id)
);

ALTER TABLE session
    ADD CONSTRAINT FK_SESSION_ON_USER_USER FOREIGN KEY (user_user_id) REFERENCES users (user_id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (roles_user_id) REFERENCES role (user_id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (users_user_id) REFERENCES users (user_id);